export default {
  1 /** 3-4-1-2 */: [
    {
      id: 0,
      posX: 50,
      posY: 10,
      positionName: 'GK',
    },
    {
      id: 1,
      posX: 25,
      posY: 28,
      positionName: 'CB',
    },
    {
      id: 2,
      posX: 50,
      posY: 28,
      positionName: 'CB',
    },
    {
      id: 3,
      posX: 75,
      posY: 28,
      positionName: 'CB',
    },
    {
      id: 4,
      posX: 37,
      posY: 45,
      positionName: 'CDM',
    },
    {
      id: 5,
      posX: 63,
      posY: 45,
      positionName: 'CDM',
    },
    {
      id: 6,
      posX: 20,
      posY: 58,
      positionName: 'LM',
    },
    {
      id: 7,
      posX: 50,
      posY: 58,
      positionName: 'CAM',
    },
    {
      id: 8,
      posX: 80,
      posY: 58,
      positionName: 'RM',
    },
    {
      id: 9,
      posX: 38,
      posY: 72,
      positionName: 'ST',
    },
    {
      id: 10,
      posX: 62,
      posY: 72,
      positionName: 'ST',
    },
  ],
  2 /** 3-4-2-1 */: [
    {
      id: 0,
      posX: 50,
      posY: 10,
      positionName: 'GK',
    },
    {
      id: 1,
      posX: 25,
      posY: 28,
      positionName: 'CB',
    },
    {
      id: 2,
      posX: 50,
      posY: 28,
      positionName: 'CB',
    },
    {
      id: 3,
      posX: 75,
      posY: 28,
      positionName: 'CB',
    },
    {
      id: 4,
      posX: 37,
      posY: 45,
      positionName: 'CM',
    },
    {
      id: 5,
      posX: 63,
      posY: 45,
      positionName: 'CM',
    },
    {
      id: 6,
      posX: 20,
      posY: 58,
      positionName: 'LM',
    },
    {
      id: 7,
      posX: 80,
      posY: 58,
      positionName: 'RM',
    },
    {
      id: 8,
      posX: 35,
      posY: 72,
      positionName: 'LF',
    },
    {
      id: 9,
      posX: 50,
      posY: 75,
      positionName: 'ST',
    },
    {
      id: 10,
      posX: 65,
      posY: 72,
      positionName: 'RF',
    },
  ],
  3 /** 3-1-4-2 */: [
    {
      id: 0,
      posX: 50,
      posY: 10,
      positionName: 'GK',
    },
    {
      id: 1,
      posX: 25,
      posY: 28,
      positionName: 'CB',
    },
    {
      id: 2,
      posX: 50,
      posY: 28,
      positionName: 'CB',
    },
    {
      id: 3,
      posX: 75,
      posY: 28,
      positionName: 'CB',
    },
    {
      id: 4,
      posX: 20,
      posY: 50,
      positionName: 'LM',
    },
    {
      id: 5,
      posX: 35,
      posY: 50,
      positionName: 'CM',
    },
    {
      id: 6,
      posX: 50,
      posY: 45,
      positionName: 'CDM',
    },
    {
      id: 7,
      posX: 65,
      posY: 50,
      positionName: 'CM',
    },
    {
      id: 8,
      posX: 80,
      posY: 50,
      positionName: 'RM',
    },
    {
      id: 9,
      posX: 40,
      posY: 72,
      positionName: 'ST',
    },
    {
      id: 10,
      posX: 60,
      posY: 72,
      positionName: 'ST',
    },
  ],
  4 /** 3-4-3 */: [
    {
      id: 0,
      posX: 50,
      posY: 10,
      positionName: 'GK',
    },
    {
      id: 1,
      posX: 25,
      posY: 28,
      positionName: 'CB',
    },
    {
      id: 2,
      posX: 50,
      posY: 28,
      positionName: 'CB',
    },
    {
      id: 3,
      posX: 75,
      posY: 28,
      positionName: 'CB',
    },
    {
      id: 4,
      posX: 20,
      posY: 54,
      positionName: 'LM',
    },
    {
      id: 5,
      posX: 38,
      posY: 49,
      positionName: 'CM',
    },
    {
      id: 6,
      posX: 62,
      posY: 49,
      positionName: 'CM',
    },

    {
      id: 7,
      posX: 80,
      posY: 54,
      positionName: 'RM',
    },
    {
      id: 8,
      posX: 30,
      posY: 72,
      positionName: 'LF',
    },
    {
      id: 9,
      posX: 50,
      posY: 74,
      positionName: 'ST',
    },
    {
      id: 10,
      posX: 70,
      posY: 72,
      positionName: 'RF',
    },
  ],
  5 /** 3-5-2 */: [
    {
      id: 0,
      posX: 50,
      posY: 10,
      positionName: 'GK',
    },
    {
      id: 1,
      posX: 25,
      posY: 28,
      positionName: 'CB',
    },
    {
      id: 2,
      posX: 50,
      posY: 28,
      positionName: 'CB',
    },
    {
      id: 3,
      posX: 75,
      posY: 28,
      positionName: 'CB',
    },
    {
      id: 4,
      posX: 20,
      posY: 54,
      positionName: 'LM',
    },
    {
      id: 5,
      posX: 38,
      posY: 45,
      positionName: 'CDM',
    },
    {
      id: 6,
      posX: 50,
      posY: 61,
      positionName: 'CAM',
    },
    {
      id: 7,
      posX: 62,
      posY: 45,
      positionName: 'CDM',
    },
    {
      id: 8,
      posX: 80,
      posY: 54,
      positionName: 'RM',
    },
    {
      id: 9,
      posX: 35,
      posY: 72,
      positionName: 'ST',
    },
    {
      id: 10,
      posX: 65,
      posY: 72,
      positionName: 'ST',
    },
  ],
  6 /** 4-1-2-1-2 */: [
    {
      id: 0,
      posX: 50,
      posY: 10,
      positionName: 'GK',
    },
    {
      id: 1,
      posX: 20,
      posY: 28,
      positionName: 'LB',
    },
    {
      id: 2,
      posX: 38,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 3,
      posX: 62,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 4,
      posX: 80,
      posY: 28,
      positionName: 'RB',
    },
    {
      id: 5,
      posX: 50,
      posY: 40,
      positionName: 'CDM',
    },
    {
      id: 6,
      posX: 25,
      posY: 50,
      positionName: 'LM',
    },
    {
      id: 7,
      posX: 75,
      posY: 50,
      positionName: 'RM',
    },
    {
      id: 8,
      posX: 50,
      posY: 57,
      positionName: 'CAM',
    },
    {
      id: 9,
      posX: 35,
      posY: 70,
      positionName: 'ST',
    },
    {
      id: 10,
      posX: 65,
      posY: 70,
      positionName: 'ST',
    },
  ],
  7 /** 4-1-2-1-2 (2) */: [
    {
      id: 0,
      posX: 50,
      posY: 10,
      positionName: 'GK',
    },
    {
      id: 1,
      posX: 20,
      posY: 28,
      positionName: 'LB',
    },
    {
      id: 2,
      posX: 38,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 3,
      posX: 62,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 4,
      posX: 80,
      posY: 28,
      positionName: 'RB',
    },
    {
      id: 5,
      posX: 50,
      posY: 40,
      positionName: 'CDM',
    },
    {
      id: 6,
      posX: 30,
      posY: 47,
      positionName: 'CM',
    },
    {
      id: 7,
      posX: 70,
      posY: 47,
      positionName: 'CM',
    },
    {
      id: 8,
      posX: 50,
      posY: 57,
      positionName: 'CAM',
    },
    {
      id: 9,
      posX: 37,
      posY: 70,
      positionName: 'ST',
    },
    {
      id: 10,
      posX: 63,
      posY: 70,
      positionName: 'ST',
    },
  ],
  8 /** 4-1-4-1 */: [
    {
      id: 0,
      posX: 50,
      posY: 10,
      positionName: 'GK',
    },
    {
      id: 1,
      posX: 20,
      posY: 28,
      positionName: 'LB',
    },
    {
      id: 2,
      posX: 38,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 3,
      posX: 62,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 4,
      posX: 80,
      posY: 28,
      positionName: 'RB',
    },
    {
      id: 5,
      posX: 50,
      posY: 38,
      positionName: 'CDM',
    },
    {
      id: 6,
      posX: 25,
      posY: 55,
      positionName: 'LM',
    },
    {
      id: 7,
      posX: 40,
      posY: 53,
      positionName: 'CM',
    },
    {
      id: 8,
      posX: 60,
      posY: 53,
      positionName: 'CM',
    },
    {
      id: 9,
      posX: 75,
      posY: 55,
      positionName: 'RM',
    },
    {
      id: 10,
      posX: 50,
      posY: 70,
      positionName: 'ST',
    },
  ],
  9 /** 4-2-3-1 */: [
    {
      id: 0,
      posX: 50,
      posY: 10,
      positionName: 'GK',
    },
    {
      id: 1,
      posX: 20,
      posY: 28,
      positionName: 'LB',
    },
    {
      id: 2,
      posX: 38,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 3,
      posX: 62,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 4,
      posX: 80,
      posY: 28,
      positionName: 'RB',
    },
    {
      id: 5,
      posX: 25,
      posY: 44,
      positionName: 'CDM',
    },
    {
      id: 6,
      posX: 75,
      posY: 44,
      positionName: 'CDM',
    },
    {
      id: 7,
      posX: 50,
      posY: 47,
      positionName: 'CAM',
    },
    {
      id: 8,
      posX: 37,
      posY: 58,
      positionName: 'CAM',
    },
    {
      id: 9,
      posX: 63,
      posY: 58,
      positionName: 'CAM',
    },
    {
      id: 10,
      posX: 50,
      posY: 70,
      positionName: 'ST',
    },
  ],
  10 /** 4-2-3-1 (2) */: [
    {
      id: 0,
      posX: 50,
      posY: 10,
      positionName: 'GK',
    },
    {
      id: 1,
      posX: 20,
      posY: 28,
      positionName: 'LB',
    },
    {
      id: 2,
      posX: 38,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 3,
      posX: 62,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 4,
      posX: 80,
      posY: 28,
      positionName: 'RB',
    },
    {
      id: 5,
      posX: 34,
      posY: 42,
      positionName: 'CDM',
    },
    {
      id: 6,
      posX: 66,
      posY: 42,
      positionName: 'CDM',
    },
    {
      id: 7,
      posX: 50,
      posY: 50,
      positionName: 'CAM',
    },
    {
      id: 8,
      posX: 25,
      posY: 58,
      positionName: 'LM',
    },
    {
      id: 9,
      posX: 75,
      posY: 58,
      positionName: 'RM',
    },
    {
      id: 10,
      posX: 50,
      posY: 70,
      positionName: 'ST',
    },
  ],
  11 /** 4-2-2-2 */: [
    {
      id: 0,
      posX: 50,
      posY: 10,
      positionName: 'GK',
    },
    {
      id: 1,
      posX: 20,
      posY: 28,
      positionName: 'LB',
    },
    {
      id: 2,
      posX: 38,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 3,
      posX: 62,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 4,
      posX: 80,
      posY: 28,
      positionName: 'RB',
    },
    {
      id: 5,
      posX: 25,
      posY: 55,
      positionName: 'CAM',
    },
    {
      id: 6,
      posX: 40,
      posY: 45,
      positionName: 'CDM',
    },
    {
      id: 7,
      posX: 60,
      posY: 45,
      positionName: 'CDM',
    },
    {
      id: 8,
      posX: 75,
      posY: 55,
      positionName: 'CAM',
    },
    {
      id: 9,
      posX: 40,
      posY: 70,
      positionName: 'ST',
    },
    {
      id: 10,
      posX: 60,
      posY: 70,
      positionName: 'ST',
    },
  ],
  12 /** 4-2-4 */: [
    {
      id: 0,
      posX: 50,
      posY: 10,
      positionName: 'GK',
    },
    {
      id: 1,
      posX: 20,
      posY: 28,
      positionName: 'LB',
    },
    {
      id: 2,
      posX: 38,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 3,
      posX: 62,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 4,
      posX: 80,
      posY: 28,
      positionName: 'RB',
    },
    {
      id: 5,
      posX: 25,
      posY: 65,
      positionName: 'LW',
    },
    {
      id: 6,
      posX: 40,
      posY: 47,
      positionName: 'CDM',
    },
    {
      id: 7,
      posX: 60,
      posY: 47,
      positionName: 'CDM',
    },
    {
      id: 8,
      posX: 75,
      posY: 65,
      positionName: 'RW',
    },
    {
      id: 9,
      posX: 40,
      posY: 70,
      positionName: 'ST',
    },
    {
      id: 10,
      posX: 60,
      posY: 70,
      positionName: 'ST',
    },
  ],
  13 /** 4-3-1-2 */: [
    {
      id: 0,
      posX: 50,
      posY: 10,
      positionName: 'GK',
    },
    {
      id: 1,
      posX: 20,
      posY: 28,
      positionName: 'LB',
    },
    {
      id: 2,
      posX: 38,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 3,
      posX: 62,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 4,
      posX: 80,
      posY: 28,
      positionName: 'RB',
    },
    {
      id: 5,
      posX: 32,
      posY: 46,
      positionName: 'CM',
    },
    {
      id: 6,
      posX: 50,
      posY: 40,
      positionName: 'CM',
    },
    {
      id: 7,
      posX: 68,
      posY: 46,
      positionName: 'CM',
    },
    {
      id: 8,
      posX: 50,
      posY: 57,
      positionName: 'CAM',
    },
    {
      id: 9,
      posX: 39,
      posY: 70,
      positionName: 'ST',
    },
    {
      id: 10,
      posX: 61,
      posY: 70,
      positionName: 'ST',
    },
  ],
  14 /** 4-1-3-2 */: [
    {
      id: 0,
      posX: 50,
      posY: 10,
      positionName: 'GK',
    },
    {
      id: 1,
      posX: 20,
      posY: 28,
      positionName: 'LB',
    },
    {
      id: 2,
      posX: 38,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 3,
      posX: 62,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 4,
      posX: 80,
      posY: 28,
      positionName: 'RB',
    },
    {
      id: 5,
      posX: 50,
      posY: 40,
      positionName: 'CDM',
    },
    {
      id: 6,
      posX: 30,
      posY: 48,
      positionName: 'LM',
    },
    {
      id: 7,
      posX: 70,
      posY: 48,
      positionName: 'RM',
    },
    {
      id: 8,
      posX: 50,
      posY: 57,
      positionName: 'CM',
    },
    {
      id: 9,
      posX: 39,
      posY: 70,
      positionName: 'ST',
    },
    {
      id: 10,
      posX: 61,
      posY: 70,
      positionName: 'ST',
    },
  ],
  15 /** 4-3-2-1 */: [
    {
      id: 0,
      posX: 50,
      posY: 10,
      positionName: 'GK',
    },
    {
      id: 1,
      posX: 20,
      posY: 28,
      positionName: 'LB',
    },
    {
      id: 2,
      posX: 38,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 3,
      posX: 62,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 4,
      posX: 80,
      posY: 28,
      positionName: 'RB',
    },
    {
      id: 5,
      posX: 50,
      posY: 47,
      positionName: 'CM',
    },
    {
      id: 6,
      posX: 30,
      posY: 47,
      positionName: 'CM',
    },
    {
      id: 7,
      posX: 70,
      posY: 47,
      positionName: 'CM',
    },
    {
      id: 8,
      posX: 35,
      posY: 68,
      positionName: 'LF',
    },
    {
      id: 9,
      posX: 50,
      posY: 70,
      positionName: 'ST',
    },
    {
      id: 10,
      posX: 65,
      posY: 68,
      positionName: 'RF',
    },
  ],
  16 /** 4-3-3 */: [
    {
      id: 0,
      posX: 50,
      posY: 10,
      positionName: 'GK',
    },
    {
      id: 1,
      posX: 20,
      posY: 28,
      positionName: 'LB',
    },
    {
      id: 2,
      posX: 38,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 3,
      posX: 62,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 4,
      posX: 80,
      posY: 28,
      positionName: 'RB',
    },
    {
      id: 5,
      posX: 30,
      posY: 47,
      positionName: 'CM',
    },
    {
      id: 6,
      posX: 50,
      posY: 47,
      positionName: 'CM',
    },
    {
      id: 7,
      posX: 70,
      posY: 47,
      positionName: 'CM',
    },
    {
      id: 8,
      posX: 28,
      posY: 69,
      positionName: 'LW',
    },
    {
      id: 9,
      posX: 50,
      posY: 70,
      positionName: 'ST',
    },
    {
      id: 10,
      posX: 72,
      posY: 69,
      positionName: 'RW',
    },
  ],
  17 /** 4-3-3 (2) */: [
    {
      id: 0,
      posX: 50,
      posY: 10,
      positionName: 'GK',
    },
    {
      id: 1,
      posX: 20,
      posY: 28,
      positionName: 'LB',
    },
    {
      id: 2,
      posX: 38,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 3,
      posX: 62,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 4,
      posX: 80,
      posY: 28,
      positionName: 'RB',
    },
    {
      id: 6,
      posX: 31,
      posY: 46,
      positionName: 'CM',
    },
    {
      id: 5,
      posX: 50,
      posY: 41,
      positionName: 'CDM',
    },
    {
      id: 7,
      posX: 69,
      posY: 46,
      positionName: 'CM',
    },
    {
      id: 8,
      posX: 28,
      posY: 69,
      positionName: 'LW',
    },
    {
      id: 9,
      posX: 50,
      posY: 70,
      positionName: 'ST',
    },
    {
      id: 10,
      posX: 72,
      posY: 69,
      positionName: 'RW',
    },
  ],
  18 /** 4-3-3 (3) */: [
    {
      id: 0,
      posX: 50,
      posY: 10,
      positionName: 'GK',
    },
    {
      id: 1,
      posX: 20,
      posY: 28,
      positionName: 'LB',
    },
    {
      id: 2,
      posX: 38,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 3,
      posX: 62,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 4,
      posX: 80,
      posY: 28,
      positionName: 'RB',
    },
    {
      id: 6,
      posX: 31,
      posY: 43,
      positionName: 'CDM',
    },
    {
      id: 5,
      posX: 50,
      posY: 45,
      positionName: 'CM',
    },
    {
      id: 7,
      posX: 69,
      posY: 43,
      positionName: 'CDM',
    },
    {
      id: 8,
      posX: 28,
      posY: 69,
      positionName: 'LW',
    },
    {
      id: 9,
      posX: 50,
      posY: 70,
      positionName: 'ST',
    },
    {
      id: 10,
      posX: 72,
      posY: 69,
      positionName: 'RW',
    },
  ],
  19 /** 4-3-3 (4) */: [
    {
      id: 0,
      posX: 50,
      posY: 10,
      positionName: 'GK',
    },
    {
      id: 1,
      posX: 20,
      posY: 28,
      positionName: 'LB',
    },
    {
      id: 2,
      posX: 38,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 3,
      posX: 62,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 4,
      posX: 80,
      posY: 28,
      positionName: 'RB',
    },
    {
      id: 6,
      posX: 31,
      posY: 45,
      positionName: 'CM',
    },
    {
      id: 5,
      posX: 50,
      posY: 48,
      positionName: 'CAM',
    },
    {
      id: 7,
      posX: 69,
      posY: 45,
      positionName: 'CM',
    },
    {
      id: 8,
      posX: 28,
      posY: 69,
      positionName: 'LW',
    },
    {
      id: 9,
      posX: 50,
      posY: 70,
      positionName: 'ST',
    },
    {
      id: 10,
      posX: 72,
      posY: 69,
      positionName: 'RW',
    },
  ],
  20 /** 4-3-3 (5) */: [
    {
      id: 0,
      posX: 50,
      posY: 10,
      positionName: 'GK',
    },
    {
      id: 1,
      posX: 20,
      posY: 28,
      positionName: 'LB',
    },
    {
      id: 2,
      posX: 38,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 3,
      posX: 62,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 4,
      posX: 80,
      posY: 28,
      positionName: 'RB',
    },
    {
      id: 6,
      posX: 31,
      posY: 46,
      positionName: 'CM',
    },
    {
      id: 5,
      posX: 50,
      posY: 41,
      positionName: 'CDM',
    },
    {
      id: 7,
      posX: 69,
      posY: 46,
      positionName: 'CM',
    },
    {
      id: 8,
      posX: 28,
      posY: 69,
      positionName: 'LW',
    },
    {
      id: 9,
      posX: 50,
      posY: 65,
      positionName: 'CF',
    },
    {
      id: 10,
      posX: 72,
      posY: 69,
      positionName: 'RW',
    },
  ],
  21 /** 4-4-1-1 */: [
    {
      id: 0,
      posX: 50,
      posY: 10,
      positionName: 'GK',
    },
    {
      id: 1,
      posX: 20,
      posY: 28,
      positionName: 'LB',
    },
    {
      id: 2,
      posX: 38,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 3,
      posX: 62,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 4,
      posX: 80,
      posY: 28,
      positionName: 'RB',
    },
    {
      id: 5,
      posX: 23,
      posY: 46,
      positionName: 'LM',
    },
    {
      id: 6,
      posX: 38,
      posY: 42,
      positionName: 'CM',
    },
    {
      id: 7,
      posX: 62,
      posY: 42,
      positionName: 'CM',
    },
    {
      id: 8,
      posX: 77,
      posY: 47,
      positionName: 'RM',
    },
    {
      id: 9,
      posX: 50,
      posY: 55,
      positionName: 'CF',
    },
    {
      id: 10,
      posX: 50,
      posY: 70,
      positionName: 'ST',
    },
  ],
  22 /** 4-4-1-1 (2) */: [
    {
      id: 0,
      posX: 50,
      posY: 10,
      positionName: 'GK',
    },
    {
      id: 1,
      posX: 20,
      posY: 28,
      positionName: 'LB',
    },
    {
      id: 2,
      posX: 38,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 3,
      posX: 62,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 4,
      posX: 80,
      posY: 28,
      positionName: 'RB',
    },
    {
      id: 5,
      posX: 23,
      posY: 46,
      positionName: 'LM',
    },
    {
      id: 6,
      posX: 38,
      posY: 42,
      positionName: 'CM',
    },
    {
      id: 7,
      posX: 62,
      posY: 42,
      positionName: 'CM',
    },
    {
      id: 8,
      posX: 77,
      posY: 47,
      positionName: 'RM',
    },
    {
      id: 9,
      posX: 50,
      posY: 51,
      positionName: 'CAM',
    },
    {
      id: 10,
      posX: 50,
      posY: 70,
      positionName: 'ST',
    },
  ],
  23 /** 4-4-2 */: [
    {
      id: 0,
      posX: 50,
      posY: 10,
      positionName: 'GK',
    },
    {
      id: 1,
      posX: 20,
      posY: 28,
      positionName: 'LB',
    },
    {
      id: 2,
      posX: 38,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 3,
      posX: 62,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 4,
      posX: 80,
      posY: 28,
      positionName: 'RB',
    },
    {
      id: 5,
      posX: 23,
      posY: 50,
      positionName: 'LM',
    },
    {
      id: 6,
      posX: 38,
      posY: 48,
      positionName: 'CM',
    },
    {
      id: 7,
      posX: 62,
      posY: 48,
      positionName: 'CM',
    },
    {
      id: 8,
      posX: 77,
      posY: 50,
      positionName: 'RM',
    },
    {
      id: 9,
      posX: 40,
      posY: 70,
      positionName: 'ST',
    },
    {
      id: 10,
      posX: 60,
      posY: 70,
      positionName: 'ST',
    },
  ],
  24 /** 4-4-2 (2) */: [
    {
      id: 0,
      posX: 50,
      posY: 10,
      positionName: 'GK',
    },
    {
      id: 1,
      posX: 20,
      posY: 28,
      positionName: 'LB',
    },
    {
      id: 2,
      posX: 38,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 3,
      posX: 62,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 4,
      posX: 80,
      posY: 28,
      positionName: 'RB',
    },
    {
      id: 5,
      posX: 23,
      posY: 53,
      positionName: 'LM',
    },
    {
      id: 6,
      posX: 38,
      posY: 45,
      positionName: 'CDM',
    },
    {
      id: 7,
      posX: 62,
      posY: 45,
      positionName: 'CDM',
    },
    {
      id: 8,
      posX: 77,
      posY: 53,
      positionName: 'RM',
    },
    {
      id: 9,
      posX: 40,
      posY: 70,
      positionName: 'ST',
    },
    {
      id: 10,
      posX: 60,
      posY: 70,
      positionName: 'ST',
    },
  ],
  25 /** 4-5-1 */: [
    {
      id: 0,
      posX: 50,
      posY: 10,
      positionName: 'GK',
    },
    {
      id: 1,
      posX: 20,
      posY: 28,
      positionName: 'LB',
    },
    {
      id: 2,
      posX: 38,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 3,
      posX: 62,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 4,
      posX: 80,
      posY: 28,
      positionName: 'RB',
    },
    {
      id: 5,
      posX: 50,
      posY: 38,
      positionName: 'CM',
    },
    {
      id: 6,
      posX: 25,
      posY: 52,
      positionName: 'LM',
    },
    {
      id: 7,
      posX: 40,
      posY: 55,
      positionName: 'CAM',
    },
    {
      id: 8,
      posX: 60,
      posY: 55,
      positionName: 'CAM',
    },
    {
      id: 9,
      posX: 75,
      posY: 52,
      positionName: 'RM',
    },
    {
      id: 10,
      posX: 50,
      posY: 70,
      positionName: 'ST',
    },
  ],
  26 /** 4-5-1 (2) */: [
    {
      id: 0,
      posX: 50,
      posY: 10,
      positionName: 'GK',
    },
    {
      id: 1,
      posX: 20,
      posY: 28,
      positionName: 'LB',
    },
    {
      id: 2,
      posX: 38,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 3,
      posX: 62,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 4,
      posX: 80,
      posY: 28,
      positionName: 'RB',
    },
    {
      id: 5,
      posX: 23,
      posY: 53,
      positionName: 'LM',
    },
    {
      id: 6,
      posX: 36,
      posY: 50,
      positionName: 'CM',
    },
    {
      id: 7,
      posX: 50,
      posY: 48,
      positionName: 'CM',
    },
    {
      id: 8,
      posX: 64,
      posY: 50,
      positionName: 'CM',
    },
    {
      id: 9,
      posX: 77,
      posY: 53,
      positionName: 'RM',
    },
    {
      id: 10,
      posX: 50,
      posY: 70,
      positionName: 'ST',
    },
  ],
  27 /** 5-2-1-2 */: [
    {
      id: 0,
      posX: 50,
      posY: 10,
      positionName: 'GK',
    },
    {
      id: 1,
      posX: 16,
      posY: 30,
      positionName: 'LWB',
    },
    {
      id: 2,
      posX: 33,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 3,
      posX: 50,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 4,
      posX: 66,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 5,
      posX: 84,
      posY: 30,
      positionName: 'RWB',
    },
    {
      id: 6,
      posX: 40,
      posY: 42,
      positionName: 'CM',
    },
    {
      id: 7,
      posX: 60,
      posY: 42,
      positionName: 'CM',
    },
    {
      id: 8,
      posX: 50,
      posY: 56,
      positionName: 'CAM',
    },
    {
      id: 9,
      posX: 38,
      posY: 70,
      positionName: 'ST',
    },
    {
      id: 10,
      posX: 62,
      posY: 70,
      positionName: 'ST',
    },
  ],
  28 /** 5-2-2-1 */: [
    {
      id: 0,
      posX: 50,
      posY: 10,
      positionName: 'GK',
    },
    {
      id: 1,
      posX: 16,
      posY: 30,
      positionName: 'LWB',
    },
    {
      id: 2,
      posX: 33,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 3,
      posX: 50,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 4,
      posX: 66,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 5,
      posX: 84,
      posY: 30,
      positionName: 'RWB',
    },
    {
      id: 6,
      posX: 40,
      posY: 50,
      positionName: 'CM',
    },
    {
      id: 7,
      posX: 60,
      posY: 50,
      positionName: 'CM',
    },
    {
      id: 8,
      posX: 28,
      posY: 68,
      positionName: 'LW',
    },
    {
      id: 9,
      posX: 50,
      posY: 70,
      positionName: 'ST',
    },
    {
      id: 10,
      posX: 72,
      posY: 68,
      positionName: 'RW',
    },
  ],
  29 /** 5-3-2 */: [
    {
      id: 0,
      posX: 50,
      posY: 10,
      positionName: 'GK',
    },
    {
      id: 1,
      posX: 16,
      posY: 30,
      positionName: 'LWB',
    },
    {
      id: 2,
      posX: 33,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 3,
      posX: 50,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 4,
      posX: 66,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 5,
      posX: 84,
      posY: 30,
      positionName: 'RWB',
    },
    {
      id: 6,
      posX: 30,
      posY: 50,
      positionName: 'CM',
    },
    {
      id: 7,
      posX: 50,
      posY: 50,
      positionName: 'CM',
    },
    {
      id: 8,
      posX: 70,
      posY: 50,
      positionName: 'CM',
    },
    {
      id: 9,
      posX: 38,
      posY: 70,
      positionName: 'ST',
    },
    {
      id: 10,
      posX: 62,
      posY: 70,
      positionName: 'ST',
    },
  ],
  30 /** 5-1-1 */: [
    {
      id: 0,
      posX: 50,
      posY: 10,
      positionName: 'GK',
    },
    {
      id: 1,
      posX: 16,
      posY: 30,
      positionName: 'LWB',
    },
    {
      id: 2,
      posX: 33,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 3,
      posX: 50,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 4,
      posX: 66,
      posY: 25,
      positionName: 'CB',
    },
    {
      id: 5,
      posX: 84,
      posY: 30,
      positionName: 'RWB',
    },
    {
      id: 6,
      posX: 25,
      posY: 55,
      positionName: 'LM',
    },
    {
      id: 7,
      posX: 40,
      posY: 48,
      positionName: 'CM',
    },
    {
      id: 8,
      posX: 60,
      posY: 48,
      positionName: 'CM',
    },
    {
      id: 9,
      posX: 75,
      posY: 55,
      positionName: 'RM',
    },
    {
      id: 10,
      posX: 50,
      posY: 70,
      positionName: 'ST',
    },
  ],
};
